# Site settings
site: Ephesus
title: Maria Vitoria Blog
keywords: Markdown, blog
description: >-
  Meu blog escrevendo e ensinando
lang: pt-BR
timezone:  Brazil/Brazilia
repo: https://github.com/vivihzg/wi.git # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Maria Vitoria
  bio: Olá, sou Maria Vitoria! Bem-vindo(a) ao meu Blog.
  picture: assets/images/profile.jpg
  github: vivihzg # github username
  instagram: vivihzg # instagram username
  email: vivihzgithub@gmail.com # email adress


# URL settings
url: baseurl="/http://vivihzg.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
